homeassistant:
  name: Hem
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  whitelist_external_dirs:
    - '/config/'

default_config:

frontend:
  themes: !include themes.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

lovelace:
  mode: yaml
  resources:
    [ {'url':'/hacsfiles/bar-card/bar-card.js',                               'type':'module'},
      {'url':'/hacsfiles/button-card/button-card.js',                         'type':'module'},
      {'url':'/hacsfiles/custom-header/custom-header.js',                     'type':'module'},
      {'url':'/hacsfiles/light-entity-card/light-entity-card.js',             'type':'js'},
      {'url':'/hacsfiles/light-popup-card/light-popup-card.js',               'type':'module'},
      {'url':'/hacsfiles/lovelace-card-mod/card-mod.js',                      'type':'module'},
      {'url':'/hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js', 'type':'module'},
      {'url':'/hacsfiles/lovelace-hui-element/hui-element.js',                'type':'module'},
      {'url':'/hacsfiles/lovelace-layout-card/layout-card.js',                'type':'module'},
      {'url':'/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js',    'type':'module'},
      {'url':'/hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js',    'type':'js'},
      {'url':'/hacsfiles/mini-graph-card/mini-graph-card-bundle.js',          'type':'module'},
      {'url':'/hacsfiles/mini-media-player/mini-media-player-bundle.js',      'type':'module'},
      {'url':'/hacsfiles/popup-backdrop-filter/popup-backdrop-filter.js',     'type':'module'},
      {'url':'/hacsfiles/stack-in-card/stack-in-card.js',                     'type':'module'},
      {'url':'/hacsfiles/swipe-card/swipe-card.js',                           'type':'module'},

      {'url':'/hacsfiles/mod/hass-bha-icons.js?v=f015ee3',                    'type':'js'},
      {'url':'/local/font.css',                                               'type':'css'} ]

logger:
  default: warning
  logs:
    braviarc.braviarc: fatal
    homeassistant.components.websocket_api: fatal
    homeassistant.components.command_line.sensor: fatal
    homeassistant.components.homekit.type_media_players: fatal
    homeassistant.components.shell_command: fatal

recorder:
  purge_keep_days: 7
  include:
    entities: 
      ['light.belysning', 'light.fonsterlampa', 'media_player.sony_bravia_tv', 'media_player.playstation_4',
       'light.datorlampa', 'light.taklampor', 'switch.dator_template', 'switch.wemo_monitorer',
       'light.mattias', 'light.sanja', 'switch.wemo_flakt', 'media_player.samsung',
       'media_player.vardagsrum', 'media_player.sovrum', 'media_player.google_nest_mini',
       'light.badrum', 'light.taklampa', 'light.kladkammare_2', 'light.hall',
       'person.mattias', 'person.sanja',
       'vacuum.xiaomi_vacuum_cleaner', 'sensor.roborock_battery_level', 'sensor.roborock_fan_speed',
       'sensor.hall_temperature', 'binary_sensor.hall_motion', 'binary_sensor.badrum_motion', 
       'binary_sensor.garderob_motion', 'binary_sensor.wemo_motion',
       'sensor.tvatta_countdown',
       'sensor.imac_cpu_per', 'sensor.imac_mem_per', 'sensor.imac_system_ssd',
       'sensor.imac_macintosh_hd', 'sensor.imac_time_machine',
       'sensor.synology_network_up', 'sensor.synology_network_down', 'sensor.aktuellt_spotpris']

person:
  - name: Mattias
    id: mattias6264b484ba6c360555c9a0547
    user_id: 1b8e4036264b484ba6c360555c9a0547
    device_trackers:
      ['device_tracker.mattias', 'device_tracker.iphone', 'device_tracker.mattias_bluetooth']

  - name: Sanja
    id: sanja4543958678435345345345345
    device_trackers:
      ['device_tracker.sanja', 'device_tracker.sanja_bluetooth']

device_tracker:
  - platform: iphonedetect
    consider_home: 120
    new_device_defaults:
      track_new_devices: false
    hosts:
      Mattias: !secret iphonedetect_mattias
      Sanja: !secret iphonedetect_sanja

  - platform: bluetooth_tracker

hue:
  bridges:
    - host: !secret hue_host
      allow_unreachable: true

wemo:
  discovery: false
  static: !secret wemo_static

media_player:
  - platform: braviatv
    host: !secret braviatv_host

cast:
  media_player:
    - host: !secret google_cast_host

samsungtv:
  - host: !secret samsungtv_host

hacs:
  token: !secret hacs_token

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

vacuum:
  - platform: xiaomi_miio
    host: !secret roborock_host
    token: !secret roborock_token

tts:
  - platform: google_translate
    language: 'sv'
    base_url: !secret tts_base_url

mqtt:
  broker: !secret mqtt_broker
  discovery: true
  discovery_prefix: homeassistant

browser_mod:
  devices:
    918296e3-e2a54976:
      name: imac_chrome
    c2080cea-6627150a:
      name: tablet

timer:
  laundry:
    duration: '01:00:00'
    icon: 'mdi:washing-machine'

binary_sensor:
  - platform: command_line
    name: check_plex
    command: !secret check_plex
    scan_interval: 300
    payload_on: "on"
    payload_off: "off"

  - platform: ping
    host: 8.8.8.8
    name: nas_internet_access

shell_command:
  # Setup on macos
  # System Preferences > Sharing > Remote Login
  # ssh root@hassio.local
  # ssh-keygen
  # /config/.ssh/id_rsa
  # ssh-copy-id -i /config/.ssh/id_rsa USER@XXX.XXX.X.X

  imac_turn_off: !secret imac_turn_off
  imac_sleep: !secret imac_sleep
  imac_restart: !secret imac_restart
  notify_motion_hall: !secret notify_motion_hall
  notify_laundry: !secret notify_laundry

  monitorer_volume_slider: !secret monitorer_volume_slider
  monitorer_mute_off: !secret monitorer_mute_off
  monitorer_mute_on: !secret monitorer_mute_on

  fullykiosk_brightness_slider: !secret fullykiosk_brightness_slider
  fullykiosk_load_start_url: !secret fullykiosk_load_start_url
  fullykiosk_restart_app: !secret fullykiosk_restart_app
  fullykiosk_screensaver_on: !secret fullykiosk_screensaver_on
  fullykiosk_screensaver_off: !secret fullykiosk_screensaver_off

  reference_click: !secret reference_click
  reference_kill: !secret reference_kill
  reference_monitors: !secret reference_monitors
  reference_headphones: !secret reference_headphones

  restart_hass_docker: !secret restart_hass_docker
  clear_logs: truncate -s 0 /config/home-assistant.log
  switchbot_rpi: !secret switchbot_rpi
  update_data_kwh: !secret update_data_kwh

group:
  ui_sound:
    entities:
      ['automation.ui_sound_on', 'automation.ui_sound_off', 'automation.ui_sound_popup']

light:
  - platform: group
    name: Belysning
    entities:
      ['light.tvlampa', 'light.golvlampa']

  - platform: group
    name: Taklampor
    entities:
      ['light.spot_1', 'light.spot_2']

  - platform: group
    name: alla_lampor_utom_hall
    entities:
      ['light.fonsterlampa', 'light.tvlampa', 'light.golvlampa', 'light.datorlampa', 
      'light.vask_hoger', 'light.vask_vanster', 'light.kladkammare_2', 'light.taklampa', 
      'light.mattias', 'light.sanja', 'light.spot_1', 'light.spot_2']

homekit:
  ip_address: !secret homekit_ip_address
  auto_start: false
  filter:
    include_entities:
      ['switch.wemo_flakt', 'switch.wemo_monitorer', 'switch.dator_template', 'media_player.sony_bravia_tv', 
      'media_player.samsung', 'switch.playstation_template', 'input_boolean.motion_hall', 
      'input_boolean.motion_garderob', 'input_boolean.motion_badrum', 
      'script.auto_hemma', 'script.auto_stang_allt']
  entity_config:
    switch.wemo_flakt:
      name: Fläkt
    switch.wemo_monitorer:
      name: Monitorer
      type: outlet
    switch.dator_template:
      name: Dator
    media_player.sony_bravia_tv:
      name: Tv
      feature_list:
        - feature: on_off
    media_player.samsung:
      name: Samsung Tv
      feature_list:
        - feature: on_off
    switch.playstation_template:
      name: Playstation
    script.auto_hemma:
      name: Hemma
    script.auto_stang_allt:
      name: Stäng allt

cloud:
  google_actions:
    filter:
      include_entities:
        ['switch.wemo_flakt', 'switch.wemo_monitorer', 'switch.dator_template', 'media_player.sony_bravia_tv', 
        'media_player.samsung', 'switch.playstation_template', 'media_player.playstation_4', 
        'switch.fullykiosk_screen', 'switch.fullykiosk_screensaver', 'script.auto_hemma', 'script.auto_stang_allt']
    entity_config:
      switch.wemo_flakt:
        name: Fläkt
        aliases:
          ['Fläkt', 'Fläkten']
        room: Sovrum
      switch.wemo_monitorer:
        name: Monitorer
        room: Studio
      switch.dator_template:
        name: Dator
        aliases:
          ['Dator', 'Datorn', 'Datan', 'iMac']
        room: Studio
      media_player.sony_bravia_tv:
        name: Tv
        aliases:
          ['Tv', 'Sony Tv', 'Sony Bravia Tv', 'Bravia Tv', 'Vardagsrums Tv', 'Vardagsrums Teven', 'Tv Vardagsrum']
        room: Vardagsrum
      media_player.samsung:
        name: Samsung Tv
        aliases:
          ['Samsung Tv', 'Sovrums Tv', 'Sovrums Teven', 'Tv Sovrum']
        room: Sovrum
      switch.playstation_template:
        name: Playstation
        aliases:
          ['Playstation', 'PS4', 'Playstation 4']
        room: Vardagsrum
      script.auto_hemma:
        name: Hemma
        aliases:
          ['Hemma', 'Auto hemma', 'Jag är hemma']
        room: Hall
      script.auto_stang_allt:
        name: Stäng allt
        aliases:
          ['Stäng allt', 'Auto Stäng allt']
        room: Hall

input_boolean:
  dator_template:
  sony_bravia_tv:
  samsung:
  playstation_template:

  lock_computer:
  krisinformation_visibility:
  laundry_timer_visibility:

  motion_hall:
    name: hallen
    initial: off
  motion_garderob:
    name: klädkammaren
    initial: off
  motion_badrum:
    name: badrummet
    initial: off

input_number:
  monitorer_volume:
    name: Volym
    icon: 'mdi:volume-high'
    initial: 20
    min: 7
    max: 75
    step: 2
    unit_of_measurement: "%"

  fullykiosk_brightness_slider:
    name: Ljusstyrka
    icon: 'mdi:brightness-percent'
    initial: 20
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"

  fan_timer:
    name: Stäng efter
    icon: 'mdi:fan-off'
    initial: 6
    min: 1
    max: 12
    step: 1
    unit_of_measurement: "h"

input_select:
  hdmi:
    name: Källa
    options:
      ['HDMI 1', 'HDMI 2/MHL', 'HDMI 3', 'HDMI 4']
    initial: HDMI 1
    icon: mdi:video-input-hdmi

  hdmi2:
    name: Källa
    options:
      ['TV', 'HDMI']
    initial: HDMI
    icon: mdi:video-input-hdmi

  ps4_game:
    name: Senast spelat
    options:
      - Inte igång...
    icon: mdi:gamepad

  roborock_fan_speed:
    name: Rengöringsläge
    options:
      ['Tyst', 'Standard','Medium', 'Turbo']
    icon: mdi:fan

  roborock_zone:
    initial: Ingen vald
    options:
      ['Ingen vald', 'Hall', 'Kök','Vardagsrum', 'Studio', 'Sovrum']

  conditional_media:
    initial: Senast nedladdat
    options:
      ['Senast nedladdat', 'Vardagsrum', 'Sovrum', 'PlayStation 4', 'Google Nest Mini']

switch:
  - platform: wake_on_lan
    mac: !secret wake_on_lan_mac_address
    name: iMac
    host: !secret wake_on_lan_host

  - platform: rest
    resource: !secret ha_dockermon_watchtower
    name: Watchtower
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: command_line
    switches:
      fullykiosk_screen:
        command_on: !secret fullykiosk_screen_on
        command_off: !secret fullykiosk_screen_off
        command_state: !secret fullykiosk_screen_state
        value_template: '{{ value == "on" }}'
        friendly_name: Fullykiosk Screen

  - platform: template
    switches:
      dator_template:
        value_template: "{{ is_state('switch.imac', 'on') }}"
        turn_on:
          service: script.dator_on
        turn_off:
          service: script.dator_off

      tv_template:
        value_template: "{{ is_state('media_player.sony_bravia_tv', 'on') }}"
        turn_on:
          service: script.tv_on
        turn_off:
          service: script.tv_off

      tv2_template:
        value_template: "{{ is_state('media_player.samsung', 'on') }}"
        turn_on:
          service: script.tv2_on
        turn_off:
          service: script.tv2_off

      playstation_template:
        friendly_name: Playstation
        value_template: "{{ is_state('sensor.ps4_state', 'on') }}"
        turn_on:
          service: script.playstation_on
        turn_off:
          service: script.playstation_off

      auto_stangallt_template:
        friendly_name: Stäng allt
        value_template: "{{ states('script.auto_stang_allt') }}"
        turn_on:
          service: script.auto_stang_allt
        turn_off:
          service: script.auto_stang_allt

      auto_hemma_template:
        friendly_name: Hemma
        value_template: "{{ states('script.auto_hemma') }}"
        turn_on:
          service: script.auto_hemma
        turn_off:
          service: script.auto_hemma

      fullykiosk_screensaver:
        value_template: >-
          {% if is_state_attr('sensor.fullykiosk', 'currentFragment', 'screensaver') %}
            on {% else %} off {% endif %}
        turn_on:
          service: shell_command.fullykiosk_screensaver_on
        turn_off:
          service: shell_command.fullykiosk_screensaver_off
