sensor:

    ####################################################
    #                                                  #
    #                     SENSOR                       #
    #                                                  #
    ####################################################

  - platform: version
    name: hass_version_installed
    source: local

  - platform: version
    name: hass_version_latest
    source: container

  - platform: version
    name: hass_version_latest_beta
    source: container
    beta: true

  - platform: filesize
    file_paths:
      - /config/home-assistant.log

  - platform: sql
    db_url: !secret recorder_db_url
    queries:
      - name: Databas
        query: >
          SELECT table_schema "database", Round(Sum(data_length + index_length) / POWER(1024,2), 1) 
          "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;
        column: value
        unit_of_measurement: MB

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: uptime

  - platform: time_date
    display_options:
      - time
      - date

  - platform: unifigateway
    username: !secret unifi_username
    password: !secret unifi_password
    host: !secret unifi_host
    version: UDMP-unifiOS
    monitored_conditions:
      - www
      - wan
      - firmware

  - platform: rest
    name: valetudo_version_latest
    resource: https://api.github.com/repos/Hypfer/Valetudo/releases/latest
    value_template: >
      {{ value_json.tag_name }}
    scan_interval: 86400

  - platform: rest
    name: tasmota_version_latest
    resource: https://api.github.com/repos/arendst/Tasmota/releases/latest
    value_template: >
      {{ value_json.tag_name.split('v')[1] }}
    scan_interval: 86400

  - platform: scrape
    name: synology_dsm_latest
    resource: https://www.synology.com/en-global/releaseNote/DSM
    select: >
      #release_notes_content > div:first-child > h3
    value_template: >
      {{ value.split(' ')[1] }}
    scan_interval: 86400

  - platform: rest
    name: kemper_latest
    resource: 'https://www.kemper-amps.com/api/update?type=RIGMANAGER'
    value_template: >
      {{ value_json.updates.item[0]['@version'] }}
    authentication: basic
    username: !secret kemper_username
    password: !secret kemper_password
    scan_interval: 86400

  - platform: command_line
    name: kemper_installed
    command: !secret kemper_installed
    scan_interval: 86400

  - platform: rest
    name: covid_19_folkhalsomyndigheten
    resource: https://www.arcgis.com/sharing/rest/content/items/2dc63e26f509468f896ec69476b0dab3/data
    value_template: >
      {{ 'Otillgänglig' if value_json.embedCode == '' else 'Tillgänglig' }}
    json_attributes_path: $.widgets.widget_1.config
    json_attributes: [embedCode]
    scan_interval: 21600

  - platform: rest
    name: skanetrafiken
    resource: !secret skanetrafiken
    value_template: >
      {{ value_json.Trip[0].LegList.Leg[1].Product.num }}
    json_attributes_path: $.Trip[0].LegList.Leg[1].Origin
    json_attributes: [name, time, date]
    scan_interval: 268

  - platform: rest
    name: hass_release_notes
    resource: https://api.github.com/repos/home-assistant/core/releases/latest
    value_template: >
      {{ value_json.name }}
    json_attributes: [body]
    scan_interval: 21600

  - platform: rest
    name: hass_release_notes_rc
    resource: https://api.github.com/repos/home-assistant/core/releases?per_page=1
    value_template: >
      {{ value_json[0].name }}
    json_attributes: [body]
    scan_interval: 21600

  - platform: dnsip

  - platform: darksky
    api_key: !secret darksky_api_key
    language: sv
    monitored_conditions:
      - temperature
      - apparent_temperature
      - precip_probability

  - platform: rest
    name: docker_cpu
    resource: !secret ha_dockermon_cpu
    value_template: >
      {% set cpuDelta = value_json.cpu_stats.cpu_usage.total_usage - value_json.precpu_stats.cpu_usage.total_usage %}
      {% set systemDelta = value_json.cpu_stats.system_cpu_usage - value_json.precpu_stats.system_cpu_usage %}
      {{ (cpuDelta / systemDelta * value_json.cpu_stats.cpu_usage.percpu_usage | length * 100) | round(1) }}
    json_attributes:
      - cpu_stats
      - precpu_stats
      - memory_stats

  - platform: plex_recently_added
    token: !secret plex_token
    host: !secret plex_host
    port: !secret plex_port
    max: 1
    img_dir: /
    image_resolution: 500

  - platform: waste_collection_schedule
    name: Sophämtning
    value_template: >
      {{ value.types | join(', ') + ' ' }}
      {% if value.daysTo == 0 %}
        idag
      {% elif value.daysTo == 1 %}
        imorgon
      {% elif value.daysTo == 2 %}
        i övermorgon
      {% else %}
        om {{ value.daysTo }} dagar
      {% endif %}

  - platform: influxdb
    api_version: 2
    ssl: false
    host: !secret influxdb_host
    port: !secret influxdb_port
    organization: !secret influxdb_org
    token: !secret influxdb_token
    queries_flux:
      - name: Mattias vikt
        unit_of_measurement: kg
        bucket: weight
        range_start: "-30d"
        group_function: last
        query: >
          filter(fn: (r) =>
            r.domain == "sensor" and
            r.entity_id == "mattias_weight" and
            r._field == "weight")

  - platform: command_line
    name: Playstation
    scan_interval: 300
    command: !secret playstation_5_state
    value_template: >
      {% if value == 'AWAKE' %}
        ON
      {% elif value == 'STANDBY' %}
        OFF
      {% else %}
        Okänd
      {% endif %}

  - platform: command_line
    name: switchbot_battery
    scan_interval: 259200
    command: !secret switchbot_battery
    unit_of_measurement: '%'

  - platform: command_line
    name: imac_ip
    scan_interval: 86400
    command: !secret imac_ip

  - platform: command_line
    name: imac_system_ssd
    scan_interval: 86400
    unit_of_measurement: '%'
    command: !secret imac_system_ssd

  - platform: command_line
    name: imac_macintosh_hd
    scan_interval: 86400
    unit_of_measurement: '%'
    command: !secret imac_macintosh_hd

  - platform: command_line
    name: imac_cpu
    scan_interval: 86400
    unit_of_measurement: '%'
    command: !secret imac_cpu

  - platform: command_line
    name: imac_mem
    scan_interval: 86400
    unit_of_measurement: '%'
    command: !secret imac_mem

  - platform: command_line
    name: monitors_volume
    scan_interval: 86400
    command: !secret monitors_update_volume

  - platform: command_line
    name: imac_uptime
    scan_interval: 86400
    command: !secret imac_uptime
    value_template: >
      {{ value | int | timestamp_custom('%Y-%m-%dT%H:%M:%S') }}
